### ISSUE TITLE
Resource not updated when bind with c#

### ISSUE THREAD

**Issue by Abesoddy** [JimmyPun610/Plugin.XF.MultiLanguage#1]
Hello,

First, thanks for this repo :) 

However i have a question, when i bind my resource from the code behind with the line below, my resource is not updating...
`btn.Text = StringLoader.Instance.GetString("ResourceKey").Value;`

Is it a bug or a normal behavior ?

**Comment by JimmyPun610** [comment]
> Hello,
> 
> First, thanks for this repo :)
> 
> However i have a question, when i bind my resource from the code behind with the line below, my resource is not updating...
> `btn.Text = StringLoader.Instance.GetString("ResourceKey").Value;`
> 
> Is it a bug or a normal behavior ?

I think it is normal behavior since you are setting the property Text to the value.

I suggest you set the binding in xaml, in case you have to set it in code behind, I guess something like
```
label.SetBinding(Label.RotationProperty, "Value");
``` 
will work. You can find more hints from the official documentation.

Another workaround is subscribe the change of the global value which represent language. You may use MessagingCenter or RX.net which I am more prefer

**Comment by Abesoddy** [comment]
Thanks for you answer, but i have my view with the xaml code below : 

             `<Button
                    Text="{Binding BtnText}"
                    HeightRequest="60"
                    Margin="0,25,0,10"
                    FontSize="Medium"
                    HorizontalOptions="FillAndExpand"
                    Command="{Binding Command}" />`

And my view model :

`BtnText = StringLoader.Instance.GetString("ResourceKey").Value;`

So i set the binding property on xaml, the resource should update no?

**Comment by JimmyPun610** [comment]
> Thanks for you answer, but i have my view with the xaml code below :
> 
> ```
>          `<Button
>                 Text="{Binding BtnText}"
>                 HeightRequest="60"
>                 Margin="0,25,0,10"
>                 FontSize="Medium"
>                 HorizontalOptions="FillAndExpand"
>                 Command="{Binding Command}" />`
> ```
> 
> And my view model :
> 
> `BtnText = StringLoader.Instance.GetString("ResourceKey").Value;`
> 
> So i set the binding property on xaml, the resource should update no?

I think it will not update. Since you are binding the string BtnText which is defined as StringLoader.Instance.GetString("ResourceKey").Value.

but this code will not run again at runtime when you change the language in runtime.
Reason here if you are interested in:
(https://stackoverflow.com/questions/25633944/string-is-value-type-or-reference-type)

I suggest you subscribe the language change in your view-model, run
```

`BtnText = StringLoader.Instance.GetString("ResourceKey").Value;`
```
again

**Comment by Abesoddy** [comment]
Ah yes indeed it is clearer, thank you very much for your answers!
